# Development override for Docker Compose
version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./back-end:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./dubhacks
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001/api
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./dubhacks:/app
      - /app/node_modules
    command: npm start