# AWS App Runner Service Configuration
# This is the easiest way to deploy without managing EC2

version: 1.0
runtime: nodejs16
build:
  commands:
    build:
      - echo "Installing dependencies"
      - npm ci
      - echo "Building application"
      - npm run build
run:
  runtime-version: 16
  command: npm start
  network:
    port: 3001
    env: PORT
  env:
    - name: NODE_ENV
      value: production
    - name: AWS_REGION
      value: us-east-1
    - name: DYNAMODB_TABLE_USERS
      value: eventsync-production-users
    - name: DYNAMODB_TABLE_EVENTS
      value: eventsync-production-events